import { createContext, useContext, useState } from 'react';

/* ─────────────────────────────────────────────────────────────── */
/*  Translations — EN | DE                                         */
/* ─────────────────────────────────────────────────────────────── */
const T = {
  EN: {
    nav: {
      home:          'Home',
      levels:        'Levels',
      vocabulary:    'Vocabulary',
      exercises:     'Exercises',
      opportunities: 'Opportunities',
      community:     'Community',
      start:         'Get Started →',
      profile:       'Profile',
      logout:        'Log out',
    },
    home: {
      badge:       'Learn German — free for everyone',
      h1a:         'Learn German',
      h1b:         'for everyone.',
      subtitle:    'The free platform to learn German — lessons, vocabulary and exercises for all.',
      subtitleDe:  'Die kostenlose Deutschlernplattform für alle.',
      cta1:        'Start now',
      cta2:        'Browse vocabulary',
      xpLabel:     (xp, lvl) => `${xp} XP earned · Level ${lvl}`,
      openBtn:     'Open →',
      categories:  ['All', 'A1', 'A2', 'Grammar', 'Vocabulary', 'Exercises', 'Lists'],
      cards: [
        { title: 'Beginner — A1',          desc: '6 lessons — greetings, numbers, family, colours…',          tag: 'A1 · 6 lessons'   },
        { title: 'Full Vocabulary',         desc: '500+ words grouped by topic — body, food, work…',           tag: '500+ words'        },
        { title: 'Interactive Exercises',   desc: 'Multiple choice, fill-in-the-blank — learn by doing.',      tag: 'Interactive'       },
        { title: 'Intermediate — A2',       desc: '5 lessons — work, city, weather, health…',                  tag: 'A2 · 5 lessons'   },
        { title: 'German Grammar',          desc: 'der / die / das — articles, conjugation, cases explained.', tag: 'Grammar'           },
        { title: 'Thematic Lists',          desc: 'Families, colours, jobs, human body — 500+ words.',         tag: 'Lists'             },
        { title: 'Progress System',         desc: 'Earn XP every lesson, level up as you improve.',            tag: 'Gamification'      },
        { title: 'Start German',            desc: 'First words, greetings, numbers — perfect for beginners.',  tag: 'A1 · Beginner'    },
      ],
      footerLinks: ['Lessons', 'Vocabulary', 'Exercises', 'Profile'],
      missionBadge: 'Our Mission',
      missionH2a: 'The German language,',
      missionH2b: 'within your reach.',
      missionPara: 'Mastering German opens professional, academic and cultural doors. DeutschLearn guides you from your first word to A2 level — structured, clear, free.',
      values: [
        { num: '01', label: 'Guided progression',  desc: 'From A1 to A2, step by step, without skipping the basics.' },
        { num: '02', label: 'Constant practice',    desc: 'Varied exercises at each lesson to reinforce learning.' },
        { num: '03', label: 'Cultural immersion',   desc: 'Language and culture, inseparably linked.' },
        { num: '04', label: 'Clarity & structure',  desc: 'Simple, well-organised content, accessible to all.' },
      ],
      visionQuote: '"Making German accessible to everyone."',
      visionSub: 'A global, welcoming community to learn together.',
      featureSubtitle: 'Learn · Progress',
      featureFree: 'Free',
      featureH3a: 'Learn German.',
      featureH3b: 'Progress together.',
      featurePara: 'A platform built for everyone — from A1 beginner to A2 confirmed. Every lesson, every exercise, every word brings you closer to fluency.',
      featureStats: ['Levels', 'Chapters', 'Free'],
      featureCta: 'Start the journey',
      practiceLabel: 'Real practice',
      practiceBody: 'Dialogues and oral exercises — everyday German.',
      kulturLabel: 'Kultur',
      kulturBody: 'Traditions, food and cities: culture at the heart of learning.',
      discoverBtn: 'Discover →',
      exploreTitle: 'Explore the platform',
      exploreSub: 'Everything you need to learn German — in one place.',
      navCards: [
        { title: 'Levels',        desc: '6 A1 chapters + 5 A2 chapters — full beginner progression.',         tag: 'Levels' },
        { title: 'Community',     desc: 'Exchange, ask questions, and progress with other learners.',          tag: 'Community' },
        { title: 'Opportunities', desc: 'Jobs, internships and language stays in Germany.',                    tag: 'Opportunities · 🇩🇪' },
        { title: 'Skills',        desc: 'Hören, Lesen, Schreiben, Sprechen.',         tag: 'Skills' },
        { title: 'Kultur',        desc: 'Traditions, food, cities and history — German culture.',              tag: 'Kultur' },
      ],
    },
    levels: {
      pageTitle:   'Levels',
      pageDecor:   'NIVEAU',
      pageSubtitle:'Choose your level and start learning.',
      progressLabel:'Progress',
      noLessons:   'No lessons available.',
      lessonLabel: 'Lesson',
      levels: [
        {
          name:    'Beginner',
          nameDe:  'Anfänger',
          desc:    'Start German — greetings, numbers, family…',
          descDe:  'Beginnen Sie mit den Grundlagen der deutschen Sprache.',
        },
        {
          name:    'Intermediate',
          nameDe:  'Grundkenntnisse',
          desc:    'Build on A1 — work, city, weather, health…',
          descDe:  'Aufbauend auf A1 — Alltag, Arbeit, Gesundheit…',
        },
      ],
    },
    vocabulary: {
      pageTitle:   'Vocabulary',
      pageDecor:   'WÖRTER',
      pageSubtitle:'500+ German words grouped by topic.',
      searchPlaceholder: 'Search a word…',
      filterAll:   'All',
      learned:     'Learned',
      notLearned:  'To learn',
      tapHint:     'Click to flip',
      deutsch:     'Deutsch',
      english:     'English',
      example:     'Example',
      learnedBadge:'Learned ✓',
      progress:    (n, t) => `${n} / ${t} words learned`,
      xpEarned:    (x) => `+${x} XP`,
    },
    exercises: {
      pageTitle:   'Exercises',
      pageDecor:   'QUIZ',
      pageSubtitle:'Test your knowledge with interactive exercises.',
      allFilter:   'All',
      score:       'Score',
      correct:     'Correct!',
      wrong:       'Wrong:',
      nextBtn:     'Next →',
      finishBtn:   'Finish',
      xpLabel:     (x) => `+${x} XP`,
      statsTitle:  'Results',
      statXP:      'Total XP',
      statCorrect: 'Correct answers',
      statLessons: 'Exercises completed',
    },
    login: {
      pageDecor:   'DEUTSCH',
      title:       'Sign in',
      subtitle:    'Sign in to continue your learning journey.',
      emailLabel:  'Email address',
      emailPH:     'your@email.com',
      passLabel:   'Password',
      passPH:      '••••••••',
      submitBtn:   'Sign in',
      loadingBtn:  'Signing in…',
      googleBtn:   'Continue with Google',
      orDivider:   'or',
      switchToReg: "No account? Sign up",
      regTitle:    'Create an account',
      regSubtitle: 'Join DeutschLearn — free forever.',
      nameLabel:   'Full name',
      namePH:      'Your name',
      confirmLabel:'Confirm password',
      confirmPH:   '••••••••',
      regBtn:      'Create account',
      regLoading:  'Creating…',
      switchToLog: 'Already have an account? Sign in',
      guestBtn:    'Continue without account →',
    },
    profile: {
      pageDecor:   'PROFIL',
      statsTitle:  'Statistics',
      achievTitle: 'Achievements',
      settingsTitle:'Settings',
      dangerTitle: 'Danger zone',
      nameLabel:   'Name',
      emailLabel:  'Email',
      saveBtn:     'Save',
      logoutBtn:   'Log out',
      deleteBtn:   'Delete account',
      xpStat:      'Total XP',
      lessonsStat: 'Lessons',
      exercisesStat:'Exercises',
      levelStat:   'Level',
    },
    footer: {
      nav:      'Navigation',
      skills:   'Skills',
      levels:   'Levels',
      contact:  'Contact',
      info:     'About',
      madeFor:  'For everyone',
      multilang:'Multilingual interface',
      openSource:'Open source',
      noAds:    'No ads',
      desc:     'Free German learning platform for everyone — from A1 to C2.',
      tagline:  'Deutschland 🇩🇪',
      levelLabels: ['Beginner', 'Elementary', 'Intermediate', 'Advanced'],
      copy:     (y) => `© ${y} DeutschLearn — For everyone`,
    },
  },

  /* ────────────────────────────── DEUTSCH ───────────────────────── */
  DE: {
    nav: {
      home:          'Startseite',
      levels:        'Niveaus',
      vocabulary:    'Wortschatz',
      exercises:     'Übungen',
      opportunities: 'Möglichkeiten',
      community:     'Community',
      start:         'Starten →',
      profile:       'Profil',
      logout:        'Abmelden',
    },
    home: {
      badge:       'The German learning platform for everyone',
      h1a:         'Lernen Sie Deutsch',
      h1b:         'für alle.',
      subtitle:    'Die kostenlose Plattform für alle — Lektionen, Wortschatz und Übungen.',
      subtitleDe:  'Learn German — free forever.',
      cta1:        'Jetzt starten',
      cta2:        'Wortschatz ansehen',
      xpLabel:     (xp, lvl) => `${xp} XP erreicht · Niveau ${lvl}`,
      openBtn:     'Öffnen →',
      categories:  ['Alle', 'A1', 'A2', 'Grammatik', 'Wortschatz', 'Übungen', 'Listen'],
      cards: [
        { title: 'Anfänger — A1',         desc: '6 Lektionen — Begrüßung, Zahlen, Familie, Farben…',            tag: 'A1 · 6 Lektionen' },
        { title: 'Vollständiger Wortschatz', desc: '500+ Wörter nach Thema — Körper, Essen, Arbeit…',           tag: '500+ Wörter'      },
        { title: 'Interaktive Übungen',   desc: 'Multiple Choice, Lückentexte — Lernen macht Spaß.',            tag: 'Interaktiv'       },
        { title: 'Fortgeschrittene — A2', desc: '5 Lektionen — Arbeit, Stadt, Wetter, Gesundheit…',             tag: 'A2 · 5 Lektionen' },
        { title: 'Deutsche Grammatik',    desc: 'der / die / das — Artikel, Konjugation, Fälle einfach erklärt.',tag: 'Grammatik'       },
        { title: 'Thematische Listen',    desc: 'Familien, Farben, Berufe, Körper — 500+ Wörter.',              tag: 'Listen'           },
        { title: 'Fortschrittssystem',    desc: 'Verdiene XP bei jeder Lektion, steige im Level auf.',          tag: 'Gamification'     },
        { title: 'Deutsch beginnen',      desc: 'Erste Wörter, Begrüßung, Zahlen — perfekt für Anfänger.',      tag: 'A1 · Anfänger'   },
      ],
      footerLinks: ['Lektionen', 'Wortschatz', 'Übungen', 'Profil'],
      missionBadge: 'Unsere Mission',
      missionH2a: 'Die deutsche Sprache,',
      missionH2b: 'zum Greifen nah.',
      missionPara: 'Deutsch zu meistern öffnet berufliche, akademische und kulturelle Türen. DeutschLearn begleitet Sie vom ersten Wort bis zum Niveau A2 — strukturiert, klar, kostenlos.',
      values: [
        { num: '01', label: 'Geführtes Lernen',     desc: 'Von A1 bis A2, Schritt für Schritt, ohne die Grundlagen zu überspringen.' },
        { num: '02', label: 'Ständige Übung',        desc: 'Abwechslungsreiche Übungen in jeder Lektion, um Gelerntes zu festigen.' },
        { num: '03', label: 'Kulturelle Immersion',  desc: 'Sprache und Kultur — untrennbar miteinander verbunden.' },
        { num: '04', label: 'Klarheit & Struktur',   desc: 'Einfacher, gut strukturierter Inhalt — für alle zugänglich.' },
      ],
      visionQuote: '"Deutsch für alle zugänglich machen."',
      visionSub: 'Eine weltweite, offene Community, die gemeinsam lernt.',
      featureSubtitle: 'Lernen · Vorankommen',
      featureFree: 'Kostenlos',
      featureH3a: 'Deutsch lernen.',
      featureH3b: 'Gemeinsam vorankommen.',
      featurePara: 'Eine Plattform für alle — vom A1-Anfänger bis zum A2-Fortgeschrittenen. Jede Lektion, jede Übung, jedes Wort bringt Sie der Sprachkompetenz näher.',
      featureStats: ['Niveaus', 'Kapitel', 'Kostenlos'],
      featureCta: 'Den Kurs starten',
      practiceLabel: 'Echte Praxis',
      practiceBody: 'Dialoge und mündliche Übungen — Deutsch des Alltags.',
      kulturLabel: 'Kultur',
      kulturBody: 'Traditionen, Küche und Städte: Kultur im Mittelpunkt des Lernens.',
      discoverBtn: 'Entdecken →',
      exploreTitle: 'Die Plattform erkunden',
      exploreSub: 'Alles, was Sie brauchen, um Deutsch zu lernen — an einem Ort.',
      navCards: [
        { title: 'Niveaus',       desc: '6 A1-Kapitel + 5 A2-Kapitel — vollständige Anfängerprogression.',      tag: 'Niveaus' },
        { title: 'Community',     desc: 'Tauschen Sie sich aus, stellen Sie Fragen und lernen Sie mit anderen.',  tag: 'Community' },
        { title: 'Möglichkeiten', desc: 'Jobs, Praktika und Sprachaufenthalte in Deutschland.',                  tag: 'Möglichkeiten · 🇩🇪' },
        { title: 'Kompetenzen',   desc: 'Hören, Lesen, Schreiben, Sprechen — die 4 Sprachkompetenzen.',         tag: 'Kompetenzen' },
        { title: 'Kultur',        desc: 'Traditionen, Küche, Städte und Geschichte — die deutsche Kultur.',      tag: 'Kultur' },
      ],
    },
    levels: {
      pageTitle:   'Niveaus',
      pageDecor:   'NIVEAU',
      pageSubtitle:'Wählen Sie Ihr Niveau und beginnen Sie zu lernen.',
      progressLabel:'Fortschritt',
      noLessons:   'Keine Lektionen verfügbar.',
      lessonLabel: 'Lektion',
      levels: [
        {
          name:    'Anfänger',
          nameDe:  'Anfänger',
          desc:    'Beginnen Sie mit Deutsch — Begrüßung, Zahlen, Familie…',
          descDe:  'Beginnen Sie mit den Grundlagen der deutschen Sprache.',
        },
        {
          name:    'Grundkenntnisse',
          nameDe:  'Grundkenntnisse',
          desc:    'Aufbauend auf A1 — Arbeit, Stadt, Wetter, Gesundheit…',
          descDe:  'Aufbauend auf A1 — Alltag, Arbeit, Gesundheit…',
        },
      ],
    },
    vocabulary: {
      pageTitle:   'Wortschatz',
      pageDecor:   'WÖRTER',
      pageSubtitle:'500+ deutsche Wörter nach Thema gruppiert.',
      searchPlaceholder: 'Wort suchen…',
      filterAll:   'Alle',
      learned:     'Gelernt',
      notLearned:  'Zu lernen',
      tapHint:     'Tippen zum Umdrehen',
      deutsch:     'Deutsch',
      english:     'Englisch',
      example:     'Beispiel',
      learnedBadge:'Gelernt ✓',
      progress:    (n, t) => `${n} / ${t} Wörter gelernt`,
      xpEarned:    (x) => `+${x} XP`,
    },
    exercises: {
      pageTitle:   'Übungen',
      pageDecor:   'QUIZ',
      pageSubtitle:'Testen Sie Ihr Wissen mit interaktiven Übungen.',
      allFilter:   'Alle',
      score:       'Punktzahl',
      correct:     'Richtig !',
      wrong:       'Falsch :',
      nextBtn:     'Weiter →',
      finishBtn:   'Fertig',
      xpLabel:     (x) => `+${x} XP`,
      statsTitle:  'Ergebnisse',
      statXP:      'Gesamt-XP',
      statCorrect: 'Richtige Antworten',
      statLessons: 'Übungen abgeschlossen',
    },
    login: {
      pageDecor:   'DEUTSCH',
      title:       'Anmelden',
      subtitle:    'Melden Sie sich an, um Ihr Lernen fortzusetzen.',
      emailLabel:  'E-Mail-Adresse',
      emailPH:     'ihre@email.com',
      passLabel:   'Passwort',
      passPH:      '••••••••',
      submitBtn:   'Anmelden',
      loadingBtn:  'Laden…',
      googleBtn:   'Mit Google fortfahren',
      orDivider:   'oder',
      switchToReg: 'Kein Konto? Registrieren',
      regTitle:    'Konto erstellen',
      regSubtitle: 'Treten Sie DeutschLearn bei — für immer kostenlos.',
      nameLabel:   'Vollständiger Name',
      namePH:      'Ihr Name',
      confirmLabel:'Passwort bestätigen',
      confirmPH:   '••••••••',
      regBtn:      'Konto erstellen',
      regLoading:  'Erstellen…',
      switchToLog: 'Schon ein Konto? Anmelden',
      guestBtn:    'Ohne Konto fortfahren →',
    },
    profile: {
      pageDecor:   'PROFIL',
      statsTitle:  'Statistiken',
      achievTitle: 'Erfolge',
      settingsTitle:'Einstellungen',
      dangerTitle: 'Gefahrenzone',
      nameLabel:   'Name',
      emailLabel:  'E-Mail',
      saveBtn:     'Speichern',
      logoutBtn:   'Abmelden',
      deleteBtn:   'Konto löschen',
      xpStat:      'Gesamt-XP',
      lessonsStat: 'Lektionen',
      exercisesStat:'Übungen',
      levelStat:   'Niveau',
    },
    footer: {
      nav:      'Navigation',
      skills:   'Kompetenzen',
      levels:   'Niveaus',
      contact:  'Kontakt',
      info:     'Über uns',
      madeFor:  'Für alle',
      multilang:'Mehrsprachige Oberfläche',
      openSource:'Open Source',
      noAds:    'Keine Werbung',
      desc:     'Kostenlose Deutschlernplattform für alle — von A1 bis C2.',
      tagline:  'Deutschland 🇩🇪',
      levelLabels: ['Anfänger', 'Grundkenntnisse', 'Mittelstufe', 'Fortgeschritten'],
      copy:     (y) => `© ${y} DeutschLearn`,
    },
  },

  /* ────────────────────────────── FRANÇAIS ───────────────────────── */
  FR: {
    nav: {
      home:          'Accueil',
      levels:        'Niveaux',
      vocabulary:    'Vocabulaire',
      exercises:     'Exercices',
      opportunities: 'Opportunités',
      community:     'Communauté',
      start:         'Commencer →',
      profile:       'Profil',
      logout:        'Se déconnecter',
    },
    home: {
      badge:       "Apprenez l'allemand — gratuit pour tous",
      h1a:         "Apprenez l'allemand",
      h1b:         'pour tous.',
      subtitle:    "La plateforme gratuite pour apprendre l'allemand — leçons, vocabulaire et exercices pour tous.",
      subtitleDe:  "Apprenez l'allemand gratuitement — du A1 au C2.",
      cta1:        'Commencer maintenant',
      cta2:        'Voir le vocabulaire',
      xpLabel:     (xp, lvl) => `${xp} XP gagnés · Niveau ${lvl}`,
      openBtn:     'Ouvrir →',
      categories:  ['Tous', 'A1', 'A2', 'Grammaire', 'Vocabulaire', 'Exercices', 'Listes'],
      cards: [
        { title: 'Débutant — A1',           desc: '6 leçons — salutations, chiffres, famille, couleurs…',           tag: 'A1 · 6 leçons'  },
        { title: 'Vocabulaire complet',      desc: '500+ mots regroupés par thème — corps, nourriture, travail…',    tag: '500+ mots'      },
        { title: 'Exercices interactifs',    desc: 'QCM, textes à trous — apprendre en pratiquant.',                 tag: 'Interactif'     },
        { title: 'Intermédiaire — A2',       desc: '5 leçons — travail, ville, météo, santé…',                       tag: 'A2 · 5 leçons'  },
        { title: 'Grammaire allemande',      desc: 'der / die / das — articles, conjugaison, cas expliqués.',        tag: 'Grammaire'      },
        { title: 'Listes thématiques',       desc: 'Familles, couleurs, métiers, corps — 500+ mots.',                tag: 'Listes'         },
        { title: 'Système de progression',   desc: 'Gagnez des XP à chaque leçon, montez de niveau.',                tag: 'Gamification'   },
        { title: 'Débuter en allemand',      desc: 'Premiers mots, salutations, chiffres — parfait pour débutants.', tag: 'A1 · Débutant'  },
      ],
      footerLinks: ['Leçons', 'Vocabulaire', 'Exercices', 'Profil'],
      missionBadge: 'Notre Mission',
      missionH2a: 'La langue allemande,',
      missionH2b: 'à votre portée.',
      missionPara: "Maîtriser l'allemand ouvre des portes professionnelles, académiques et culturelles. DeutschLearn vous accompagne du premier mot jusqu'au niveau A2 — structuré, clair, gratuit.",
      values: [
        { num: '01', label: 'Progression guidée',   desc: 'Du A1 au A2, étape par étape, sans sauter les bases.' },
        { num: '02', label: 'Pratique constante',    desc: 'Exercices variés à chaque leçon pour ancrer les acquis.' },
        { num: '03', label: 'Immersion culturelle',  desc: 'Langue et culture, indissociablement liées.' },
        { num: '04', label: 'Clarté & structure',    desc: 'Contenu simple, bien organisé, accessible à tous.' },
      ],
      visionQuote: '"Rendre l\'allemand accessible à tous."',
      visionSub: 'Une communauté mondiale et bienveillante pour apprendre ensemble.',
      featureSubtitle: 'Apprendre · Progresser',
      featureFree: 'Gratuit',
      featureH3a: "Apprendre l'allemand.",
      featureH3b: 'Progresser ensemble.',
      featurePara: "Une plateforme construite pour tous — du A1 débutant au A2 confirmé. Chaque leçon, chaque exercice, chaque mot vous rapproche de la fluidité.",
      featureStats: ['Niveaux', 'Chapitres', 'Gratuit'],
      featureCta: 'Commencer le parcours',
      practiceLabel: 'Pratique réelle',
      practiceBody: "Dialogues et exercices oraux — l'allemand du quotidien.",
      kulturLabel: 'Kultur',
      kulturBody: "Traditions, cuisine et villes : la culture au cœur de l'apprentissage.",
      discoverBtn: 'Découvrir →',
      exploreTitle: 'Explorer la plateforme',
      exploreSub: "Tout ce dont vous avez besoin pour apprendre l'allemand — en un seul endroit.",
      navCards: [
        { title: 'Niveaux',      desc: '6 chapitres A1 + 5 chapitres A2 — progression complète du débutant.',       tag: 'Niveaux' },
        { title: 'Communauté',   desc: "Échangez, posez des questions et progressez avec d'autres apprenants.",      tag: 'Communauté' },
        { title: 'Opportunités', desc: "Offres d'emploi, stages et séjours linguistiques en Allemagne.",             tag: 'Opportunités · 🇩🇪' },
        { title: 'Compétences',  desc: 'Hören, Lesen, Schreiben, Sprechen — les 4 aptitudes langagières.',          tag: 'Compétences' },
        { title: 'Kultur',       desc: 'Traditions, cuisine, villes et histoire — la culture allemande.',            tag: 'Kultur' },
      ],
    },
    levels: {
      pageTitle:    'Niveaux',
      pageDecor:    'NIVEAU',
      pageSubtitle: 'Choisissez votre niveau et commencez à apprendre.',
      progressLabel:'Progression',
      noLessons:    'Aucune leçon disponible.',
      lessonLabel:  'Leçon',
      levels: [
        {
          name:   'Débutant',
          nameDe: 'Anfänger',
          desc:   "Commencez l'allemand — salutations, chiffres, famille…",
          descDe: 'Beginnen Sie mit den Grundlagen der deutschen Sprache.',
        },
        {
          name:   'Intermédiaire',
          nameDe: 'Grundkenntnisse',
          desc:   "Appuyez sur l'A1 — travail, ville, météo, santé…",
          descDe: 'Aufbauend auf A1 — Alltag, Arbeit, Gesundheit…',
        },
      ],
    },
    vocabulary: {
      pageTitle:         'Vocabulaire',
      pageDecor:         'WÖRTER',
      pageSubtitle:      '500+ mots allemands regroupés par thème.',
      searchPlaceholder: 'Rechercher un mot…',
      filterAll:         'Tous',
      learned:           'Appris',
      notLearned:        'À apprendre',
      tapHint:           'Cliquer pour retourner',
      deutsch:           'Deutsch',
      english:           'Français',
      example:           'Exemple',
      learnedBadge:      'Appris ✓',
      progress:          (n, t) => `${n} / ${t} mots appris`,
      xpEarned:          (x) => `+${x} XP`,
    },
    exercises: {
      pageTitle:    'Exercices',
      pageDecor:    'QUIZ',
      pageSubtitle: 'Testez vos connaissances avec des exercices interactifs.',
      allFilter:    'Tous',
      score:        'Score',
      correct:      'Correct !',
      wrong:        'Faux :',
      nextBtn:      'Suivant →',
      finishBtn:    'Terminer',
      xpLabel:      (x) => `+${x} XP`,
      statsTitle:   'Résultats',
      statXP:       'Total XP',
      statCorrect:  'Bonnes réponses',
      statLessons:  'Exercices terminés',
    },
    login: {
      pageDecor:   'DEUTSCH',
      title:       'Se connecter',
      subtitle:    'Connectez-vous pour continuer votre apprentissage.',
      emailLabel:  'Adresse email',
      emailPH:     'votre@email.com',
      passLabel:   'Mot de passe',
      passPH:      '••••••••',
      submitBtn:   'Se connecter',
      loadingBtn:  'Connexion…',
      googleBtn:   'Continuer avec Google',
      orDivider:   'ou',
      switchToReg: "Pas de compte ? S'inscrire",
      regTitle:    'Créer un compte',
      regSubtitle: 'Rejoindre DeutschLearn — gratuit pour toujours.',
      nameLabel:   'Nom complet',
      namePH:      'Votre nom',
      confirmLabel:'Confirmer le mot de passe',
      confirmPH:   '••••••••',
      regBtn:      'Créer un compte',
      regLoading:  'Création…',
      switchToLog: 'Déjà un compte ? Se connecter',
      guestBtn:    'Continuer sans compte →',
    },
    profile: {
      pageDecor:    'PROFIL',
      statsTitle:   'Statistiques',
      achievTitle:  'Réalisations',
      settingsTitle:'Paramètres',
      dangerTitle:  'Zone de danger',
      nameLabel:    'Nom',
      emailLabel:   'Email',
      saveBtn:      'Enregistrer',
      logoutBtn:    'Se déconnecter',
      deleteBtn:    'Supprimer le compte',
      xpStat:       'Total XP',
      lessonsStat:  'Leçons',
      exercisesStat:'Exercices',
      levelStat:    'Niveau',
    },
    footer: {
      nav:      'Navigation',
      skills:   'Compétences',
      levels:   'Niveaux',
      contact:  'Contact',
      info:     'À propos',
      madeFor:  'Pour tous',
      multilang:'Interface multilingue',
      openSource:'Open source',
      noAds:    'Sans publicité',
      desc:     "Plateforme gratuite pour apprendre l'allemand — du A1 au C2.",
      tagline:  'Deutschland 🇩🇪',
      levelLabels: ['Débutant', 'Élémentaire', 'Intermédiaire', 'Avancé'],
      copy:     (y) => `© ${y} DeutschLearn`,
    },
  },
};

/* ─────────────────────────────────────────────────────────────── */
const LanguageContext = createContext(null);
const STORAGE_KEY = 'deutschmg_lang';

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      return saved === 'MG' ? 'FR' : (['EN', 'DE', 'FR'].includes(saved) ? saved : 'FR');
    } catch { return 'FR'; }
  });

  const changeLang = (code) => {
    setLang(code);
    try { localStorage.setItem(STORAGE_KEY, code); } catch { /* noop */ }
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t: T[lang] ?? T.FR, allLangs: ['EN', 'DE', 'FR'] }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
};

export default LanguageContext;
