import { createContext, useContext, useState } from 'react';

/* ─────────────────────────────────────────────────────────────── */
/*  Translations — FR | MG | DE                                    */
/* ─────────────────────────────────────────────────────────────── */
const T = {
  FR: {
    nav: {
      home:       'Accueil',
      lessons:    'Leçons',
      vocabulary: 'Vocabulaire',
      exercises:  'Exercices',
      start:      'Commencer →',
      profile:    'Profil',
      logout:     'Déconnexion',
    },
    home: {
      badge:       "Plateforme d'apprentissage de l'allemand pour les Malagasy",
      h1a:         "Apprenez l'Allemand",
      h1b:         'en Malagasy.',
      subtitle:    "La plateforme gratuite pour Malgaches qui apprennent l'allemand — leçons, vocabulaire et exercices.",
      subtitleDe:  'Die kostenlose Lernplattform für Madagassen.',
      cta1:        'Commencer maintenant',
      cta2:        'Voir le vocabulaire',
      xpLabel:     (xp, lvl) => `${xp} XP gagnés · Niveau ${lvl}`,
      openBtn:     'Ouvrir →',
      categories:  ['Tout', 'A1', 'A2', 'Grammaire', 'Vocabulaire', 'Exercices', 'Listes'],
      cards: [
        { title: 'Fanombohana — A1',     desc: '6 leçons — salutations, chiffres, famille, couleurs…',           tag: 'A1 · 6 leçons'    },
        { title: 'Vocabulaire Complet',  desc: '500+ mots groupés par thème — corps, nourriture, travail…',      tag: '500+ mots'       },
        { title: 'Exercices Interactifs',desc: 'QCM, remplissez les blancs — apprendre en s\'amusant.',          tag: 'Interactif'      },
        { title: 'Mioha — A2',           desc: '5 leçons — travail, ville, météo, santé…',                       tag: 'A2 · 5 leçons'   },
        { title: 'Grammaire Allemande',  desc: 'der / die / das — articles, conjugaison, cas expliqués.',        tag: 'Grammaire'       },
        { title: 'Listes Thématiques',   desc: 'Familles, couleurs, métiers, corps humain — 500+ mots.',         tag: 'Listes'          },
        { title: 'Système de Progression',desc: 'Gagne des XP à chaque leçon, monte de niveau.',                tag: 'Gamification'    },
        { title: 'Débuter en Allemand',  desc: 'Premiers mots, salutations, chiffres — parfait pour démarrer.', tag: 'A1 · Débutant'   },
      ],
      footerLinks: ['Leçons', 'Vocabulaire', 'Exercices', 'Profil'],
    },
    levels: {
      pageTitle:   'Niveaux',
      pageDecor:   'NIVEAU',
      pageSubtitle:'Choisissez votre niveau et commencez à apprendre.',
      progressLabel:'Progression',
      noLessons:   'Aucune leçon disponible.',
      lessonLabel: 'Leçon',
      levels: [
        {
          name:    'Fanombohana',
          nameDe:  'Anfänger',
          desc:    "Commencez l'allemand — salutations, chiffres, famille…",
          descDe:  'Beginnen Sie mit den Grundlagen der deutschen Sprache.',
        },
        {
          name:    'Mioha',
          nameDe:  'Grundkenntnisse',
          desc:    'Construire sur A1 — travail, ville, météo, santé…',
          descDe:  'Aufbauend auf A1 — Alltag, Arbeit, Gesundheit…',
        },
      ],
    },
    vocabulary: {
      pageTitle:   'Vocabulaire',
      pageDecor:   'WÖRTER',
      pageSubtitle:'500+ mots allemands groupés par thème.',
      searchPlaceholder: 'Rechercher un mot…',
      filterAll:   'Tout',
      learned:     'Appris',
      notLearned:  'À apprendre',
      tapHint:     'Appuyer pour retourner',
      deutsch:     'Deutsch',
      malagasy:    'Malagasy',
      example:     'Exemple',
      learnedBadge:'Appris ✓',
      progress:    (n, t) => `${n} / ${t} mots appris`,
      xpEarned:    (x) => `+${x} XP`,
    },
    exercises: {
      pageTitle:   'Exercices',
      pageDecor:   'QUIZ',
      pageSubtitle:'Testez vos connaissances avec des exercices interactifs.',
      allFilter:   'Tout',
      score:       'Score',
      correct:     'Correcte !',
      wrong:       'Faux :',
      nextBtn:     'Suivant →',
      finishBtn:   'Terminer',
      xpLabel:     (x) => `+${x} XP`,
      statsTitle:  'Résultats',
      statXP:      'XP Total',
      statCorrect: 'Réponses correctes',
      statLessons: 'Exercices terminés',
    },
    login: {
      pageDecor:   'DEUTSCH',
      title:       'Connexion',
      subtitle:    'Connectez-vous pour continuer votre apprentissage.',
      emailLabel:  'Adresse e-mail',
      emailPH:     'votre@email.com',
      passLabel:   'Mot de passe',
      passPH:      '••••••••',
      submitBtn:   'Se connecter',
      loadingBtn:  'Connexion…',
      googleBtn:   'Continuer avec Google',
      orDivider:   'ou',
      switchToReg: "Pas encore de compte ? S'inscrire",
      regTitle:    'Créer un compte',
      regSubtitle: 'Rejoignez DeutschMG — gratuit pour toujours.',
      nameLabel:   'Nom complet',
      namePH:      'Votre nom',
      confirmLabel:'Confirmer le mot de passe',
      confirmPH:   '••••••••',
      regBtn:      'Créer mon compte',
      regLoading:  'Création…',
      switchToLog: 'Déjà un compte ? Se connecter',
      guestBtn:    'Continuer sans compte →',
    },
    profile: {
      pageDecor:   'PROFIL',
      statsTitle:  'Statistiques',
      achievTitle: 'Succès',
      settingsTitle:'Paramètres',
      dangerTitle: 'Zone de danger',
      nameLabel:   'Nom',
      emailLabel:  'E-mail',
      saveBtn:     'Sauvegarder',
      logoutBtn:   'Se déconnecter',
      deleteBtn:   'Supprimer le compte',
      xpStat:      'XP Total',
      lessonsStat: 'Leçons',
      exercisesStat:'Exercices',
      levelStat:   'Niveau',
    },
    footer: {
      nav:      'Navigation',
      levels:   'Niveaux',
      info:     'À propos',
      madeFor:  'Fait pour les Malagasy',
      multilang:'Interface multilingue',
      openSource:'Open source',
      noAds:    'Aucune publicité',
      copy:     (y) => `© ${y} DeutschMG`,
    },
  },

  /* ───────────────────────────── MALAGASY ───────────────────────── */
  MG: {
    nav: {
      home:       'Fanombohana',
      lessons:    'Lesona',
      vocabulary: 'Teny',
      exercises:  'Fanaovana',
      start:      'Atombohy →',
      profile:    'Profily',
      logout:     'Hivoaka',
    },
    home: {
      badge:       'Sehatra fianarana ny teny Alemà ho an\'ny Malagasy',
      h1a:         'Mianara ny Teny Alemà',
      h1b:         'amin\'ny Malagasy.',
      subtitle:    'Sehatra maimaim-poana ho an\'ny Malagasy mianatra ny teny Alemà — lesona, teny ary fanaovana.',
      subtitleDe:  'Die kostenlose Lernplattform für Madagassen.',
      cta1:        'Atombohy izao',
      cta2:        'Jereo ny teny',
      xpLabel:     (xp, lvl) => `${xp} XP voaray · Ambaratonga ${lvl}`,
      openBtn:     'Jereo →',
      categories:  ['Rehetra', 'A1', 'A2', 'Tsianjery', 'Teny', 'Fanaovana', 'Lisitra'],
      cards: [
        { title: 'Fanombohana — A1',     desc: '6 lesona — fiarahabana, isa, fianakaviana, loko…',              tag: 'A1 · 6 lesona'  },
        { title: 'Teny Feno',            desc: 'Teny 500+ voatokana — vatana, sakafo, asa…',                    tag: '500+ teny'      },
        { title: 'Fanaovana Mifanerana', desc: 'Safidy maro, fenoy banga — mampianatra am-pifaliako.',          tag: 'Mifanerana'     },
        { title: 'Mioha — A2',           desc: '5 lesona — asa, tanàna, toetr\'andro, fahasalamana…',           tag: 'A2 · 5 lesona'  },
        { title: 'Tsianjery Alemà',      desc: 'der / die / das — lahateny, fisakanana voalaza.',               tag: 'Tsianjery'      },
        { title: 'Lisitra Ara-lohahevitra',desc: 'Fianakaviana, loko, asa, vatana — teny 500+.',               tag: 'Lisitra'        },
        { title: 'Rafitra Fandrosoana',  desc: 'Mahazo XP amin\'ny lesona tsirairay, miakatra ambaratonga.',   tag: 'Gamification'   },
        { title: 'Atombohy ny Alemà',    desc: 'Teny voalohany, fiarahabana, isa — tsara ho an\'ny mpianatra.', tag: 'A1 · Mpianatra' },
      ],
      footerLinks: ['Lesona', 'Teny', 'Fanaovana', 'Profily'],
    },
    levels: {
      pageTitle:   'Ambaratonga',
      pageDecor:   'NIVEAU',
      pageSubtitle:'Safidio ny ambaratongany ary atombohy ny fianarana.',
      progressLabel:'Fandrosoana',
      noLessons:   'Tsy misy lesona.',
      lessonLabel: 'Lesona',
      levels: [
        {
          name:    'Fanombohana',
          nameDe:  'Anfänger',
          desc:    'Atombohy ny teny Alemà — fiarahabana, isa, fianakaviana…',
          descDe:  'Beginnen Sie mit den Grundlagen der deutschen Sprache.',
        },
        {
          name:    'Mioha',
          nameDe:  'Grundkenntnisse',
          desc:    "Rivotra ny A1 — asa, tanàna, toetr'andro, fahasalamana…",
          descDe:  'Aufbauend auf A1 — Alltag, Arbeit, Gesundheit…',
        },
      ],
    },
    vocabulary: {
      pageTitle:   'Teny',
      pageDecor:   'WÖRTER',
      pageSubtitle:'Teny Alemà 500+ voatokana ara-lohahevitra.',
      searchPlaceholder: 'Hitady teny…',
      filterAll:   'Rehetra',
      learned:     'Efa fantatra',
      notLearned:  'Tsy mbola fantatra',
      tapHint:     'Tsindrio mba hiova',
      deutsch:     'Deutsch',
      malagasy:    'Malagasy',
      example:     'Ohatra',
      learnedBadge:'Efa fantatra ✓',
      progress:    (n, t) => `${n} / ${t} teny efa fantatra`,
      xpEarned:    (x) => `+${x} XP`,
    },
    exercises: {
      pageTitle:   'Fanaovana',
      pageDecor:   'QUIZ',
      pageSubtitle:'Andranio ny fahalalana amin\'ny fanaovana mifanerana.',
      allFilter:   'Rehetra',
      score:       'Nahazoana',
      correct:     'Marina !',
      wrong:       'Diso :',
      nextBtn:     'Manaraka →',
      finishBtn:   'Vita',
      xpLabel:     (x) => `+${x} XP`,
      statsTitle:  'Vokatra',
      statXP:      'XP Rehetra',
      statCorrect: 'Valiny Marina',
      statLessons: 'Fanaovana vita',
    },
    login: {
      pageDecor:   'DEUTSCH',
      title:       'Hiditra',
      subtitle:    'Hiditra mba hanohy ny fianarana.',
      emailLabel:  'Adiresy email',
      emailPH:     'anao@email.com',
      passLabel:   'Tenimiafina',
      passPH:      '••••••••',
      submitBtn:   'Hiditra',
      loadingBtn:  'Miandry…',
      googleBtn:   'Hiditra amin\'ny Google',
      orDivider:   'na',
      switchToReg: 'Tsy manana kaonty ? Mamorona',
      regTitle:    'Mamorona kaonty',
      regSubtitle: 'Midira ao DeutschMG — maimaim-poana.',
      nameLabel:   'Anarana feno',
      namePH:      'Ny anaranao',
      confirmLabel:'Manamarina tenimiafina',
      confirmPH:   '••••••••',
      regBtn:      'Mamorona kaontiko',
      regLoading:  'Famoronana…',
      switchToLog: 'Efa manana kaonty ? Hiditra',
      guestBtn:    'Mizotra tsy misy kaonty →',
    },
    profile: {
      pageDecor:   'PROFILY',
      statsTitle:  'Statistika',
      achievTitle: 'Voninahitra',
      settingsTitle:'Fananganana',
      dangerTitle: 'Faritra Mampidi-doza',
      nameLabel:   'Anarana',
      emailLabel:  'Email',
      saveBtn:     'Tehirizo',
      logoutBtn:   'Hivoaka',
      deleteBtn:   'Fafao ny kaonty',
      xpStat:      'XP Rehetra',
      lessonsStat: 'Lesona',
      exercisesStat:'Fanaovana',
      levelStat:   'Ambaratonga',
    },
    footer: {
      nav:      'Fitondrana',
      levels:   'Ambaratonga',
      info:     'Momba',
      madeFor:  'Nataon\'ny Malagasy',
      multilang:'Teny maro',
      openSource:'Loharanon-dehibe',
      noAds:    'Tsy misy dokam-barotra',
      copy:     (y) => `© ${y} DeutschMG`,
    },
  },

  /* ────────────────────────────── DEUTSCH ───────────────────────── */
  DE: {
    nav: {
      home:       'Startseite',
      lessons:    'Lektionen',
      vocabulary: 'Wortschatz',
      exercises:  'Übungen',
      start:      'Starten →',
      profile:    'Profil',
      logout:     'Abmelden',
    },
    home: {
      badge:       'Die Deutschlernplattform für Madagassen',
      h1a:         'Lernen Sie Deutsch',
      h1b:         'auf Malagasy.',
      subtitle:    'Die kostenlose Plattform für Madagassen — Lektionen, Wortschatz und Übungen.',
      subtitleDe:  'Mianara ny Teny Alemà — maimaim-poana.',
      cta1:        'Jetzt starten',
      cta2:        'Wortschatz ansehen',
      xpLabel:     (xp, lvl) => `${xp} XP erreicht · Niveau ${lvl}`,
      openBtn:     'Öffnen →',
      categories:  ['Alle', 'A1', 'A2', 'Grammatik', 'Wortschatz', 'Übungen', 'Listen'],
      cards: [
        { title: 'Fanombohana — A1',  desc: '6 Lektionen — Begrüßung, Zahlen, Familie, Farben…',            tag: 'A1 · 6 Lektionen' },
        { title: 'Vollständiger Wortschatz', desc: '500+ Wörter nach Thema — Körper, Essen, Arbeit…',       tag: '500+ Wörter'      },
        { title: 'Interaktive Übungen',desc: 'Multiple Choice, Lückentexte — Lernen macht Spaß.',           tag: 'Interaktiv'       },
        { title: 'Mioha — A2',        desc: '5 Lektionen — Arbeit, Stadt, Wetter, Gesundheit…',             tag: 'A2 · 5 Lektionen' },
        { title: 'Deutsche Grammatik',desc: 'der / die / das — Artikel, Konjugation, Fälle einfach erklärt.',tag: 'Grammatik'       },
        { title: 'Thematische Listen',desc: 'Familien, Farben, Berufe, Körper — 500+ Wörter.',              tag: 'Listen'           },
        { title: 'Fortschrittssystem',desc: 'Verdiene XP bei jeder Lektion, steige im Level auf.',          tag: 'Gamification'     },
        { title: 'Deutsch beginnen',  desc: 'Erste Wörter, Begrüßung, Zahlen — perfekt für Anfänger.',      tag: 'A1 · Anfänger'   },
      ],
      footerLinks: ['Lektionen', 'Wortschatz', 'Übungen', 'Profil'],
    },
    levels: {
      pageTitle:   'Niveaus',
      pageDecor:   'NIVEAU',
      pageSubtitle:'Wählen Sie Ihr Niveau und beginnen Sie zu lernen.',
      progressLabel:'Fortschritt',
      noLessons:   'Keine Lektionen verfügbar.',
      lessonLabel: 'Lektion',
      levels: [
        {
          name:    'Fanombohana',
          nameDe:  'Anfänger',
          desc:    'Beginnen Sie mit Deutsch — Begrüßung, Zahlen, Familie…',
          descDe:  'Beginnen Sie mit den Grundlagen der deutschen Sprache.',
        },
        {
          name:    'Mioha',
          nameDe:  'Grundkenntnisse',
          desc:    'Aufbauend auf A1 — Arbeit, Stadt, Wetter, Gesundheit…',
          descDe:  'Aufbauend auf A1 — Alltag, Arbeit, Gesundheit…',
        },
      ],
    },
    vocabulary: {
      pageTitle:   'Wortschatz',
      pageDecor:   'WÖRTER',
      pageSubtitle:'500+ deutsche Wörter nach Thema gruppiert.',
      searchPlaceholder: 'Wort suchen…',
      filterAll:   'Alle',
      learned:     'Gelernt',
      notLearned:  'Zu lernen',
      tapHint:     'Tippen zum Umdrehen',
      deutsch:     'Deutsch',
      malagasy:    'Malagasy',
      example:     'Beispiel',
      learnedBadge:'Gelernt ✓',
      progress:    (n, t) => `${n} / ${t} Wörter gelernt`,
      xpEarned:    (x) => `+${x} XP`,
    },
    exercises: {
      pageTitle:   'Übungen',
      pageDecor:   'QUIZ',
      pageSubtitle:'Testen Sie Ihr Wissen mit interaktiven Übungen.',
      allFilter:   'Alle',
      score:       'Punktzahl',
      correct:     'Richtig !',
      wrong:       'Falsch :',
      nextBtn:     'Weiter →',
      finishBtn:   'Fertig',
      xpLabel:     (x) => `+${x} XP`,
      statsTitle:  'Ergebnisse',
      statXP:      'Gesamt-XP',
      statCorrect: 'Richtige Antworten',
      statLessons: 'Übungen abgeschlossen',
    },
    login: {
      pageDecor:   'DEUTSCH',
      title:       'Anmelden',
      subtitle:    'Melden Sie sich an, um Ihr Lernen fortzusetzen.',
      emailLabel:  'E-Mail-Adresse',
      emailPH:     'ihre@email.com',
      passLabel:   'Passwort',
      passPH:      '••••••••',
      submitBtn:   'Anmelden',
      loadingBtn:  'Laden…',
      googleBtn:   'Mit Google fortfahren',
      orDivider:   'oder',
      switchToReg: 'Kein Konto? Registrieren',
      regTitle:    'Konto erstellen',
      regSubtitle: 'Treten Sie DeutschMG bei — für immer kostenlos.',
      nameLabel:   'Vollständiger Name',
      namePH:      'Ihr Name',
      confirmLabel:'Passwort bestätigen',
      confirmPH:   '••••••••',
      regBtn:      'Konto erstellen',
      regLoading:  'Erstellen…',
      switchToLog: 'Schon ein Konto? Anmelden',
      guestBtn:    'Ohne Konto fortfahren →',
    },
    profile: {
      pageDecor:   'PROFIL',
      statsTitle:  'Statistiken',
      achievTitle: 'Erfolge',
      settingsTitle:'Einstellungen',
      dangerTitle: 'Gefahrenzone',
      nameLabel:   'Name',
      emailLabel:  'E-Mail',
      saveBtn:     'Speichern',
      logoutBtn:   'Abmelden',
      deleteBtn:   'Konto löschen',
      xpStat:      'Gesamt-XP',
      lessonsStat: 'Lektionen',
      exercisesStat:'Übungen',
      levelStat:   'Niveau',
    },
    footer: {
      nav:      'Navigation',
      levels:   'Niveaus',
      info:     'Über uns',
      madeFor:  'Für Madagassen',
      multilang:'Mehrsprachige Oberfläche',
      openSource:'Open Source',
      noAds:    'Keine Werbung',
      copy:     (y) => `© ${y} DeutschMG`,
    },
  },
};

/* ─────────────────────────────────────────────────────────────── */
const LanguageContext = createContext(null);
const STORAGE_KEY = 'deutschmg_lang';

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem(STORAGE_KEY) || 'FR'; } catch { return 'FR'; }
  });

  const changeLang = (code) => {
    setLang(code);
    try { localStorage.setItem(STORAGE_KEY, code); } catch { /* noop */ }
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t: T[lang] ?? T.FR, allLangs: ['FR', 'MG', 'DE'] }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
};

export default LanguageContext;
